### ISSUE TITLE
Feedback RubyHW/HW5-6/blog/

### ISSUE THREAD

**Issue by oleksiimikhno** [alinajuly/RubyHW#10]
Гарне рішення з params status https://github.com/alinajuly/RubyHW/blob/main/HW5-6/blog/app/models/comment.rb#L5

але можливо дуже довге рішення перевірки https://github.com/alinajuly/RubyHW/blob/main/HW5-6/blog/app/controllers/api/v1/comments_controller.rb#L5

- [x] не знайшов спосіб як змінити статус комменту

**Comment by alinajuly** [comment]
дякую, добавила опис у readme файл
