### ISSUE TITLE
HW 6 feedback

### ISSUE THREAD

**Issue by LVALL** [alinajuly/RubyHW#11]
Дуже хороша робота, мені подобається чистота коду, так тримати 🚀 

- [x] `Comment.statuses.keys.include?(params[:status])` - лаконічний та красивий спосіб для даної перевірки, хоча в цілому не надто коректна ідея. Якщо юзер введе некоректний статус - отримає всі коментарі, відповідно для нього це так, наче всі коментарі мають статус, який він ввів.

Для роботи з фільтрацією в RoR використовують query pattern, з ним ми ще попрацюємо пізніше, але можна уже ознайомитись [тут](https://medium.flatstack.com/query-object-in-ruby-on-rails-56ea434365f0)

Але так, як у нас всього один пункт для фільтрації - патерн для нас буде надлишковим. 

Можна зробити щось типу:

```
  def index
    @comments = Comment.all
    @comments = Comment.with_status(params[:status]) if params[:status].present?
    
    render json: @comments
  end
```

Якщо параметр фільтрації за статусом не передано - віддаємо всі записи, якщо передано - робимо пошук.
Якщо параметр некоректний - то користувач в результаті отримає порожню вибірку, що цілком логічно.

- [x] пропущений відступ [тут](https://github.com/alinajuly/RubyHW/blob/8d12260b4d70181d10ea9413ee48df860b78622f/HW5-6/blog/app/controllers/api/v1/comments_controller.rb#L35)

- [x] атрибут location передається для редіректу, не думаю, що він нам потрібен в API. [Код тут](https://github.com/alinajuly/RubyHW/blob/8d12260b4d70181d10ea9413ee48df860b78622f/HW5-6/blog/app/controllers/api/v1/comments_controller.rb#L17)

**Comment by alinajuly** [comment]
Дякую! 

Виправила.
