### ISSUE TITLE
 RubyHW/HW7/blog/

### ISSUE THREAD

**Issue by oleksiimikhno** [alinajuly/RubyHW#12]
- [x]  я думаю такий код можна записати як один массив https://github.com/alinajuly/RubyHW/blob/main/HW5-6-7/blog/db/seeds.rb#L9-L18

Наприклад `Author.create([{ name: 'Irina Sarapina' }, { name: 'Nataliia Kolesnikova' }])`, чи вивести  тікі масиви окремо і відправляти на створення

- [x] https://github.com/alinajuly/RubyHW/blob/main/HW5-6-7/blog/app/models/tag.rb#L5 я б додав валідацію ще на унікальність тегів
- [x] https://github.com/alinajuly/RubyHW/blob/main/HW5-6-7/blog/app/models/article.rb#L7 можна було б перепробити код. 
В тебе передає вже сущ. екземпляр через клас, що вже схоже не такий код `Article.last_ten_comments(Article.find(:id)) ` який потім вже в скопе робить фільтр `Article.find(:id).last(10)` і смисла от цього скопа немає, з такім успіхом виконати в контроллері `@article.comments.last(10)`, тому на мою думку це лишній код і навантаження. Я би зробив через таке рішення `@article.comments.last_ten_comments`
В модулі комментів `scope :last_ten_comments, -> { order(created_at: :desc).limit(10) }`

А так наче все добре і гарно))

**Comment by alinajuly** [comment]
Дякую, рефакторинг виконала :blush:
