### ISSUE TITLE
Feedback for HW7

### ISSUE THREAD

**Issue by MaksHostroushko** [alinajuly/RubyHW#13]
Looks great!
Let me show you some places for improvements

1. https://github.com/alinajuly/RubyHW/blob/main/HW5-6-7/blog/app/models/article.rb#L4
Please, update the name for your join table
We should do it readable and understandable
I mean, `article_tags` instead of `articletags `
You can read here https://guides.rubyonrails.org/association_basics.html for a little bit more info

2. https://github.com/alinajuly/RubyHW/blob/main/HW5-6-7/blog/app/models/comment.rb#L10..L12
I believe, we can use the same validations for multiple columns
It this case our code will be more readable
`validates :article_id, : author_id, :body presence: true`

**Comment by alinajuly** [comment]
Thank you, have been updated.
