### ISSUE TITLE
Feedback HW9

### ISSUE THREAD

**Issue by Haidamac** [alinajuly/RubyHW#16]
Great job!!!

Pay attention for 2 bugs in your work:
- [x] You made a mistake in the name of the article search parameter. This parameter in articles_controller isn't match parameter in articles_spec. Change this mistake in 3 places of articles_spec and your tests of articles search (manual and automatic) will be work correctly
- [x] Comments#show method don't work, because you forgot to specify it in ... ;)

And also pay attention for README.md
- [x] You can't run ```rails rswag``` after the server has started (```rails s```). Switch these commands places

**Comment by alinajuly** [comment]
Thank you, all done :)
