### ISSUE TITLE
Feedback HW 11

### ISSUE THREAD

**Issue by setwith** [alinajuly/RubyHW#19]
Добре виконана робота 🙂
Маю декілька мінорних правок

**_Моделі:_**
- [x] Варто змінити валідацію ціни продукта, оскільки ціна навряд може бути 0
greater_than_or_equal_to: 0 змінити на greater_than: 0

- [x] Напевно в моделях з рейшенами has_many краще замість [belongs_to
](dependent: :nullify) використовувати
 ```ruby 
 dependent: destroy
```

**_Контроллери_**:
- [x] Думаю, варто модифікувати метод current_cart в _application_controller_
 ```ruby 
 def current_cart
    Cart.find(cookies[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Cart.create
    cookies[:cart_id] = cart.id
    cart
  end
 ```
 Оскільки він зберігає в кукі ід корзини, залогінившись з іншого акаунта можемо перейти в корзину попереднього юзера

**_Вюхи:_**
- [x] При натисканні Proceed to payment і зміні статуса, можливо варто було б перенаправляти юзера на головну сторіку, або на сторінку ордерів

- [x] Для кращої читабельності, я б радив не додавати класи в application.html.erb, залишити лише:
 ```ruby 
<%= render partial: "layouts/template/sidebar" %>
<%= render partial: "layouts/template/navbar" %>
<%= render partial: "layouts/template/flash_message" %>
<%= yield %>
```
А класи прописувати в самих паршалах

- [x] Варто краще організувати розміщення елементів на сторінках, оскільки деякі елементи накладаються один на одний (ціна та кнопка додати до корзини не доступні на деяких продуктах оскільки перекриваються іншими пролуктами)

- [x] За допомогобю грідів можна оргінізувати елементи верстки. також це може допомогти відділити сайдбар від мейн контенту
https://getbootstrap.com/docs/5.0/layout/grid/

**Comment by alinajuly** [comment]
Дякую, виправила все, крім application_controller. На практиці юзер з цим не зіткнеться.
