### ISSUE TITLE
HW3 feedback

### ISSUE THREAD

**Issue by Haidamac** [alinajuly/RubyHW#2]
### Tamagotchi review

**Very good job!** The game works correctly. The program generates an html-file according to the task.
Original presentation of information with specially selected emojis and information line about the actions of game hero.

Pay attention to some comments and recommendations to improve your program:

- [x] No emoji is displayed at the end of the game. The reason is that you are pasting the emoji picture into the program code, not the html dec- or HEX-code (see f.e. [https://www.w3schools.com/html/html_emojis.asp](https://www.w3schools.com/html/html_emojis.asp) )

- [x] Your heroes get hungry very quickly (want to drink, sleep, etc.). For a closer resemblance to the original Tamagotchi game, functionality based on the Time class could be added (see f.e.  [https://ruby-doc.org/core-2.6.3/Time.html](https://ruby-doc.org/core-2.6.3/Time.html)

Best regards, Haidamac

**Comment by alinajuly** [comment]
Thank you!
Replaced the emoji with dec-code.
Changed the indicators for a more interesting game.
