### ISSUE TITLE
Feedback HW 12

### ISSUE THREAD

**Issue by setwith** [alinajuly/RubyHW#20]
Хороша робота! Проте можна застосувати декілька мінорних правок)

- [x] Можна добавити annotate gem, для зручності розуміння взаємозв'язків між моделями

- [x] Варто додати в модель Сart  has_one :order, dependent: :destroy , адже ордер не можу існувти без корзини. з поточною логікою не можна видалити корзину
<img width="1011" alt="Знімок екрана 2023-01-19 о 12 36 06" src="https://user-images.githubusercontent.com/93925872/213431220-a1e9555f-60d5-4768-b427-eaf113c1ced8.png">
Такий ж звязок в моделі category 

- [x] #21

відповідно можна також спростити код тут
https://github.com/alinajuly/RubyHW/blob/095322b7a4ed845b63e8761ea9d33ecac3a40537/HW12/shop/app/views/orders/show.html.erb#L12 
- [x] Для кращої читабельності, я б радив не додавати класи в application.html.erb, залишити лише:
 ```ruby 
<%= render partial: "layouts/template/sidebar" %>
<%= render partial: "layouts/template/navbar" %>
<%= render partial: "layouts/template/flash_message" %>
<%= yield %>
```

- [x] На ідекс сторінці продуктів айтеми накладаються один на одну
<img width="1434" alt="Знімок екрана 2023-01-19 о 13 25 44" src="https://user-images.githubusercontent.com/93925872/213431719-ac67a94b-8dd7-4af0-9752-8e65355d07a2.png">
виправити це можна змінивши код в _products_index  на такий:

 ```ruby 
<div class='container'>
    <div class='row g-5 d-flex justify-content-center align-items-center vh-100'>
      <% @products.each do |product| %>
        <div class='col-auto'>
          <div class='card text-bg-dark' style='width: 18rem'>
            <img src=<%= product.image %> class="card-img-top" alt=<%= product.name %>>
            <div class='card-body'>
              <h5 class='card-title text-center'><%= link_to product.name, product %></h5>
              <p class='card-price text-white'><%= number_to_currency(product.price) %></p>
              <% if current_user %>
                <%= button_to 'Add to cart', line_items_path(product_id: product.id), class: 'btn btn-warning text-end' %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>
```

**Comment by alinajuly** [comment]
Дякую.

Без класів в application.html.erb некоректно відображаються sidebar та navbar. Прописувала класи в самих файлах, вони не працюють таким чином.
