### ISSUE TITLE
Feedback HW 10

### ISSUE THREAD

**Issue by LVALL** [alinajuly/RubyHW#22]
1) Для того, щоб не доводилось екранувати апострофи в тексті, достатньо огортати строку подвійними лапками. (помітив в сід-файлі)

2) Код виглядатиме значно чистіше та читабельніше, коли в ньому не буде зайвих коментарів. (Мова йде про коментарі, автоматично згенеровані, такі є наприклад в register-файлах адмін панелі).
app/admin/products.rb має виглядати так:
```
ActiveAdmin.register Product do
  permit_params ...
end
```
всього три строки замість 18. Так само в інших файлах

3) У контролері продуктів при rescue ActiveRecord::RecordNotFound рендериться json. У монолітних проектах json не рендериться зазвичай, особливо в before фільтрах.
Достатньо залишити:
```
def set_product
  @product = Product.find(params[:id])
end
```
у такому випадку, при роботі в production-моді буде відрендерена дефолтна 404 сторінка (файл якої лежить в `public/404.html`)
про кастомні сторінки ерорів докладніше можна почитати [тут](https://web-crunch.com/posts/custom-error-page-ruby-on-rails)

4) роути варто групувати, в першу чергу - сторонні роути, потім визначений root, а далі - всі інші. 
```
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  
  root 'products#index'
  
  resources :products
  resources :categories
end
```
так буде трохи охайніше

5) На сторінці авторизації варто прибрати кнопку `log in` з хедера, так як вона редіректитиме на цю ж сторінку, що не має сенсу.

6) до форми авторизації варто додати опрацювання та вивід ерор-меседжів, щоб було зрозуміло, який з параметрів введено некоректно

7) На індексі продуктів немає можливості проскролити список, нижні елементи обрізаються, назви частково перекриваються
![image](https://user-images.githubusercontent.com/49117430/213925799-ef39cf80-cb99-4a7b-8cb9-fe5fe48bd81c.png)

**Comment by alinajuly** [comment]
Дякую, дещо було виправлено в наступних роботах, абсолютно всі зауваження виправила в останній роботі HW13.
