### ISSUE TITLE
feedback HW2 task 1

### ISSUE THREAD

**Issue by LVALL** [alinajuly/RubyHW#3]
## Завдання 1:
- [x] у завданні сказано: "видалити всі непарні числа;", `select` вибирає значення. Спробуйте метод  https://apidock.com/ruby/OptionParser/reject

В іншому - все виконано коректно та з використанням потрібних методів

**Comment by alinajuly** [comment]
Дякую, використала метод reject, рішення задачі

`array.reject(&:odd?)`

**Comment by EugeneShitov** [comment]
`select` і `reject` роблять протилежне один-одному.
В задачі просять видалити, тому рекомендую використати `map.delete_if`

**Comment by alinajuly** [comment]
дякую, використала delete_if
