### ISSUE TITLE
Feedback HW2 task 2

### ISSUE THREAD

**Issue by LVALL** [alinajuly/RubyHW#4]
## Завдання 2

- [x] одним з основних принципів програмування є DRY (Don't Repeat Yourself), тобто за можливості уникати повторів у логіці та ізолювати ідентичні дії.
  У вашому кейсі:
```
  @life += 10
  @love += 10
  @joy += 10 
```
повторюється дуже часто, варто подумати над оптимізацією. Як варіант - створити окремий приватний метод, що прийматиме значення необхідних параметрів в параметрах та в тілі методу виконуватиме їх зміну

- [x] виконання коду за умовою
```
    hunger < 60 && puts('I want to eat')
```
коректним є написання спершу дії, яку ми хочемо виконати, а після - умови 
```
  puts('I want to eat') if hunger < 60
```

- [x] для методів, назва яких закінчується знаком питання, обов'язковим є повернення булевого значення
тобто 
```
  def hungry?
    hunger < 60 && puts('I want to eat')
  end
```
не є семантично коректним і повинен бути названим інакше, або все ж повертати булеве значення
```
  def hungry?
    hunger < 60
  end
```

**Comment by alinajuly** [comment]
Дякую, виправила усі зауваження.
