### ISSUE TITLE
Feedback HW4

### ISSUE THREAD

**Issue by Kashoid23** [alinajuly/RubyHW#7]
Дуже хороший підхід до структури та організації коду!

Просто цікаво - десь піддивились, чи хтось допоміг?

- [x]  Оновіть код таким чино, щоб позбутись дублювання `.to_i <= 0`
```
  def dead?
    hunger.to_i <= 0 || thirst.to_i <= 0 || joy.to_i <= 0 || love.to_i <= 0 || tired.to_i <= 0
  end
```
- [x] Використайте attr_reader, щою позбутись окремих методів display_error та text_error
```
    def initialize(display:, text:)
      @display = display
      @text = text
    end

    def display_error
      @display
    end

    def text_error
      @text
    end
```
- [x] Ніколи не пуште закоментований код, якщо це не коментарі з поясненням коду, або TODO
```
    # PETS = {
    #   cat: Cat,
    #   rabbit: Dog,
    #   dog: Rabbit
    # }
```
- [x] Подумайте, як можна уникнути дублювання
`ERB.new(File.read(...)).result(binding)`
та
`[status, { 'Content-Type' => 'text/html' }, [...]]`

- [x] Видаліть зайвий мета тег [app](https://github.com/alinajuly/RubyHW/tree/main/HW4/tamagotchi_with_rack/app)/[views](https://github.com/alinajuly/RubyHW/tree/main/HW4/tamagotchi_with_rack/app/views)/page.html.erb
```
<meta charset="UTF-8">
    <meta charset="utf-8">
```

- [x] Оновіть код таким чином, щоб вам не доводилось кожен раз при виклику метода екземпляру додатково конвертувати результат в інтеджер `.to_i`
```
          <input type="hidden" id="tired" name="tired" value="<%= @pet.tired.to_i + 20 %>">
          <input type="hidden" id="thirst" name="thirst" value="<%= @pet.thirst.to_i - 20 %>">
          <input type="hidden" id="hunger" name="hunger" value="<%= @pet.hunger.to_i - 20 %>">
          <input type="hidden" id="love" name="love" value="<%= @pet.love.to_i - 10 %>">
```

**Comment by alinajuly** [comment]
Дякую. В гуглі та гітхабі багато інформації по тамагочі, тому так, дивилась, як роблять інші.

Код виправила згідно зауважень.

**Comment by Kashoid23** [comment]
Круто! Гарна робота! 💯
